### ISSUE TITLE
Cannot read property 'resource' of undefined

### ISSUE THREAD

**Issue by Jy496** [ant-design/antd-moment-webpack-plugin#11]
getting below erroe after adding @ant-design/moment-webpack-plugin to webpackConfig file
Html Webpack Plugin:
  Error: Child compilation failed:
  Entry module not found: TypeError: Cannot read property 'resource' of undefined:
  TypeError: Cannot read property 'resource' of undefined
  
  - compiler.js:141 
    [duke-web-app]/[html-webpack-plugin]/lib/compiler.js:141:18
  
  - Compiler.js:343 
    [duke-web-app]/[webpack]/lib/Compiler.js:343:11
  
  - Compiler.js:681 
    [duke-web-app]/[webpack]/lib/Compiler.js:681:15
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [duke-web-app]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:678 
    [duke-web-app]/[webpack]/lib/Compiler.js:678:31
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [duke-web-app]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1423 
    [duke-web-app]/[webpack]/lib/Compilation.js:1423:35

**Comment by SSSliangfeng** [comment]
I meet the same issue after add moment-webpack-plugin

**Comment by Jad2wizard** [comment]
> I meet the same issue after add moment-webpack-plugin

I also encounter this error

**Comment by mhesham93** [comment]
Same issue here, not working with Ant 5.9.1

**Comment by runningincircle** [comment]
Same here guys. Does anyone know where is key to the problem?

**Comment by runningincircle** [comment]
Ah, It looks like it only works with webpack 5

**Comment by mhesham93** [comment]
I’m using webpack 5 and still unable to get it to work. I have craco in my project, not sure if it’s causing it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leedorian** [comment]
Same here.

**Comment by xuanhieu1479** [comment]
It is due to this line in the lib
`const createData = result.createData`
`createData` is undefined causing the line below it `if (generateRegExp.test(createData.resource))` to crash.

Fork this repo and update it to
`const createData = result.createData ?? result;`

You might also need to provide { disableDayjsAlias: true } as options.

**Comment by JPM709** [comment]
I am unable to change the line above in my node_modules for a number of reasons. Though it does stop the error encountered, the build fails later due to other dependencies. I am on webpack 4, and no plans to update right now. An update would be totally rad.
In the meantime, Ant D has a way to extend DatePicker (TimePicker, etc.) using moment, you can find it in [Ant's Custom Library Docs](https://ant.design/docs/react/use-custom-date-library#datepicker)

`import { DatePicker } from 'antd';
import type { Moment } from 'moment';
import momentGenerateConfig from 'rc-picker/lib/generate/moment';

const MyDatePicker = DatePicker.generatePicker<Moment>(momentGenerateConfig);

export default MyDatePicker;
`
